import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { VirtualKeyboard } from "@/components/virtual-keyboard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR" suppressHydrationWarning>
            <body>
                <Provider>
                    {children}
                    {/* Fica em todas as telas porque a administracao tambem e
                        feita na tela do armario, onde nao ha teclado fisico.
                        Comeca escondido: so aparece ao tocar no botao. */}
                    <VirtualKeyboard />
                </Provider>
            </body>
        </html>
    );
}
