import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { ViewTransition } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_BR" suppressHydrationWarning>
      <body>
        <Provider>
          <ViewTransition>
            {children}
          </ViewTransition>
        </Provider>
      </body>
    </html>
  );
}
